CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  industry TEXT,
  template_used TEXT,
  aps_count INTEGER,
  coverage TEXT,
  avg_rssi TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- (Opcional) Índice para búsquedas rápidas por email
CREATE INDEX idx_leads_email ON leads(email);

-- Como la tabla ya existe, no es necesario crearla nuevamente. Si deseas agregar más columnas o modificar la estructura, puedes usar ALTER TABLE.

-- 1. Añadir columnas específicas para RF (si no existen)
ALTER TABLE public.leads 
ADD COLUMN IF NOT EXISTS industry TEXT,
ADD COLUMN IF NOT EXISTS template_used TEXT,
ADD COLUMN IF NOT EXISTS aps_count INTEGER,
ADD COLUMN IF NOT EXISTS coverage NUMERIC,           -- porcentaje (ej. 92.5)
ADD COLUMN IF NOT EXISTS avg_rssi NUMERIC,           -- dBm (ej. -52)
ADD COLUMN IF NOT EXISTS metadata JSONB,             -- almacena posiciones de APs, versión, etc.
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. Índice para búsquedas frecuentes por email (si no existe)
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads (email);

-- 3. Índice para filtrar por fecha y producto (útil para análisis)
CREATE INDEX IF NOT EXISTS idx_leads_product_timestamp ON public.leads (product, timestamp DESC);

-- Como la tabla existent tienes datos, para actualizar el producto

UPDATE public.leads 
SET product = 'rf_optimizer' 
WHERE product IS NULL AND type IS NOT NULL;  -- Ajusta según tu lógica